// updateIndex.js
const fs = require('fs');
const path = require('path');
const cheerio = require('cheerio');

// Detect whether repo uses docs/ for GitHub Pages
const rootDir = fs.existsSync(path.join(__dirname, 'docs')) ? path.join(__dirname, 'docs') : __dirname;
const postDir = path.join(rootDir, 'post');
const indexHtmlPath = path.join(rootDir, 'index.html');

console.log("📂 Root directory:", rootDir);
console.log("📂 Post directory:", postDir);
console.log("📄 Index HTML path:", indexHtmlPath);

// Check if post folder exists
if (!fs.existsSync(postDir)) {
    console.error("❌ ERROR: Post directory not found.");
    process.exit(1);
}

// Get latest post file
const files = fs.readdirSync(postDir)
    .filter(f => f.endsWith('.html'))
    .map(f => ({ name: f, time: fs.statSync(path.join(postDir, f)).mtime }))
    .sort((a, b) => b.time - a.time);

if (files.length === 0) {
    console.error("❌ No HTML files found in post directory.");
    process.exit(0);
}

const latestPostFile = files[0].name;
console.log("🆕 Latest post file detected:", latestPostFile);

// Read latest post HTML
const latestPostHtml = fs.readFileSync(path.join(postDir, latestPostFile), 'utf8');
const $post = cheerio.load(latestPostHtml);

// Extract details (adjust selectors if needed)
const imageUrl = $post('img').attr('src') || '';
const imgAlt = $post('img').attr('alt') || 'Blog Image';
const title = $post('h1').text().trim() || 'Untitled Post';
const excerpt = $post('p').first().text().trim().slice(0, 100) + '...';

console.log("🖼 Image:", imageUrl);
console.log("📝 Title:", title);
console.log("📄 Excerpt:", excerpt);

// Read index.html
if (!fs.existsSync(indexHtmlPath)) {
    console.error("❌ index.html not found at", indexHtmlPath);
    process.exit(1);
}
const indexHtml = fs.readFileSync(indexHtmlPath, 'utf8');
const $ = cheerio.load(indexHtml);

// Create new post card HTML
const newPostHtml = `
<div class="col-md-4 mb-4 blog-post" data-page="1">
    <div class="card">
        <div class="card-img-top">
            <img src="${imageUrl}" class="img-fluid" alt="${imgAlt}" loading="lazy">
            <div class="card-img-overlay">${title}</div>
        </div>
        <div class="card-body">
            <h5 class="card-title">${title}</h5>
            <p class="card-text">${excerpt}</p>
            <a href="post/${latestPostFile}" class="btn btn-custom read-more">Read More</a>
            <div class="social-share mt-3">
                <a href="#"><i class="fab fa-twitter"></i></a>
                <a href="#"><i class="fab fa-facebook-f"></i></a>
                <a href="#"><i class="fab fa-pinterest"></i></a>
            </div>
        </div>
    </div>
</div>
`;

// Remove any duplicate if the same post exists
$('.blog-post').each(function () {
    if ($(this).find('a.read-more').attr('href') === `post/${latestPostFile}`) {
        console.log("⚠️ Duplicate found — removing old entry.");
        $(this).remove();
    }
});

// Insert new post at the top
$('.blog-post').first().before(newPostHtml);

fs.writeFileSync(indexHtmlPath, $.html(), 'utf8');
console.log("✅ index.html updated with latest post.");
