name: Update posts.json

on:
  push:
    paths:
      - "post/**.html"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update posts.json
        run: |
          echo "[" > posts.json
          first=true
          for file in $(ls -t post/*.html); do
            title=$(grep -oP '(?<=<title>).*?(?=</title>)' "$file" | head -n 1)
            excerpt=$(grep -oP '(?<=<p>).*?(?=</p>)' "$file" | head -n 1)
            date=$(git log -1 --format="%ad" --date=short -- "$file")
            url="$file"
            image=""
            if [ "$first" = true ]; then
              first=false
            else
              echo "," >> posts.json
            fi
            echo "  {\"title\": \"$title\", \"excerpt\": \"$excerpt\", \"image\": \"$image\", \"url\": \"$url\", \"date\": \"$date\"}" >> posts.json
          done
          echo "]" >> posts.json

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add posts.json
          git commit -m "Auto-update posts.json" || echo "No changes"
          git push
